baseURL = "https://paradigmsage.com"
languageCode = "en-us"
title = "Paradigm Sage"

[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      table = true

disableKinds = ["taxonomy", "taxonomyTerm"]

